repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]

  - repo: local
    hooks:
      - id: block-c-binaries
        name: Bloquear binários/artefatos de build
        language: fail
        entry: "Não commitar binários/artefatos: .o .out .a .so app build/ bin/"
        files: '(^|/)(app|build/.*|bin/.*|.*\.(o|out|a|so))$'